# Notebook 2 — Reconstruction des cycles et agrégation par cycle pour Test 9 Run 1 à 3

Ce notebook part des fichiers CSV déjà extraits dans :

`C:\Users\elvas\Downloads\Stage de recherche\extracted_test9_run1`

Les objectifs sont :

1. Charger les fichiers `pwm`, `steady` et `transient` pour **Test 9 Run 1 à 3**
2. Reprendre la **même logique que dans ton notebook**
3. Reconstruire `cycle_current` à partir du signal `gateState` du bloc `pwm`
4. Associer chaque ligne du bloc `steady` au cycle correspondant grâce au temps (`timeEpoch`)
5. Agréger les données **par cycle dans chaque run**
6. Afficher :
   - le tableau agrégé du **Run 1**
   - le tableau agrégé du **Run 2**
   - le tableau agrégé du **Run 3**
   - le tableau concaténé final

## Logique générale

On adopte ici une logique de type **Unit / Cycle** :

- **Unit = run_id**
- **Cycle = cycle_current**
- **1 ligne finale = 1 cycle d'un run**

Cela signifie que le modèle verra ensuite plusieurs séquences temporelles, une par run, sans mélanger artificiellement les runs dans une même séquence.

In [1]:
import os
import re
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

pd.set_option("display.max_columns", 200)
pd.set_option("display.max_rows", 200)

## 1. Paramètres

Tu peux modifier `DATA_DIR` si besoin, mais ici il pointe déjà vers ton dossier d'extraction.

In [2]:
DATA_DIR = r"C:\Users\elvas\Downloads\Stage de recherche\extracted_test9_run1"

RUN_IDS = [1, 2, 3,4,5,6,7]
TEST_ID = 9

CURRENT_MIN = 1.0      # filtre simple sur le courant pour éviter V/I instable
SHOW_PLOTS = True

## 2. Vérification des fichiers disponibles

In [3]:
expected_files = []
for run_id in RUN_IDS:
    prefix = f"Test_{TEST_ID}_run_{run_id}"
    expected_files.extend([
        os.path.join(DATA_DIR, f"{prefix}_pwm.csv"),
        os.path.join(DATA_DIR, f"{prefix}_steady.csv"),
        os.path.join(DATA_DIR, f"{prefix}_transient.csv"),
    ])

check_df = pd.DataFrame({
    "file_path": expected_files,
    "exists": [os.path.exists(fp) for fp in expected_files]
})

display(check_df)

                                            file_path  exists
0   C:\Users\elvas\Downloads\Stage de recherche\ex...    True
1   C:\Users\elvas\Downloads\Stage de recherche\ex...    True
2   C:\Users\elvas\Downloads\Stage de recherche\ex...    True
3   C:\Users\elvas\Downloads\Stage de recherche\ex...    True
4   C:\Users\elvas\Downloads\Stage de recherche\ex...    True
5   C:\Users\elvas\Downloads\Stage de recherche\ex...    True
6   C:\Users\elvas\Downloads\Stage de recherche\ex...    True
7   C:\Users\elvas\Downloads\Stage de recherche\ex...    True
8   C:\Users\elvas\Downloads\Stage de recherche\ex...    True
9   C:\Users\elvas\Downloads\Stage de recherche\ex...    True
10  C:\Users\elvas\Downloads\Stage de recherche\ex...    True
11  C:\Users\elvas\Downloads\Stage de recherche\ex...    True
12  C:\Users\elvas\Downloads\Stage de recherche\ex...    True
13  C:\Users\elvas\Downloads\Stage de recherche\ex...    True
14  C:\Users\elvas\Downloads\Stage de recherche\ex...    True
15  C:\Users\elvas\Downloads\Stage de recherche\ex...    True
16  C:\Users\elvas\Downloads\Stage de recherche\ex...    True
17  C:\Users\elvas\Downloads\Stage de recherche\ex...    True
18  C:\Users\elvas\Downloads\Stage de recherche\ex...    True
19  C:\Users\elvas\Downloads\Stage de recherche\ex...    True
20  C:\Users\elvas\Downloads\Stage de recherche\ex...    True

## 3. Fonctions utilitaires

### 3.1 Chargement des trois blocs d'un run

Cette fonction charge les trois CSV :
- `pwm`
- `steady`
- `transient`

Le bloc `transient` est chargé pour vérification, mais dans cette étape la reconstruction des cycles et l'agrégation se font surtout avec `pwm` et `steady`.

In [4]:
def load_run_csvs(data_dir, test_id, run_id):
    prefix = f"Test_{test_id}_run_{run_id}"
    fp_pwm = os.path.join(data_dir, f"{prefix}_pwm.csv")
    fp_steady = os.path.join(data_dir, f"{prefix}_steady.csv")
    fp_transient = os.path.join(data_dir, f"{prefix}_transient.csv")

    df_pwm = pd.read_csv(fp_pwm)
    df_steady = pd.read_csv(fp_steady)
    df_transient = pd.read_csv(fp_transient)

    return df_pwm, df_steady, df_transient

### 3.2 Détection robuste des colonnes

Comme les noms peuvent varier légèrement d'un export à l'autre, on cherche les colonnes de manière souple.

In [5]:
def find_column(columns, candidates, required=True):
    cols_lower = {c.lower(): c for c in columns}

    for cand in candidates:
        cand_low = cand.lower()
        if cand_low in cols_lower:
            return cols_lower[cand_low]

    # recherche partielle
    for c in columns:
        c_low = c.lower()
        for cand in candidates:
            if cand.lower() in c_low:
                return c

    if required:
        raise KeyError(f"Impossible de trouver une colonne parmi : {candidates}")
    return None

### 3.3 Reconstruction du cycle à partir de `pwm`

On reprend la logique de ton notebook :

1. convertir `gateState` en variable binaire
2. détecter les **fronts montants** 0 → 1
3. faire un **cumul** des fronts montants pour obtenir `cycle_current`

Ainsi :
- chaque front montant = début d'un nouveau cycle
- le compteur de cycle augmente de 1 à chaque nouveau cycle

In [6]:
def reconstruct_cycles_from_pwm(df_pwm):
    df_pwm = df_pwm.copy()

    time_col = find_column(df_pwm.columns, ["timeEpoch", "time_epoch", "time"])
    gate_col = find_column(df_pwm.columns, ["gateState", "gate_state"])

    df_pwm[time_col] = pd.to_numeric(df_pwm[time_col], errors="coerce")
    df_pwm[gate_col] = pd.to_numeric(df_pwm[gate_col], errors="coerce")

    df_pwm = df_pwm.dropna(subset=[time_col]).sort_values(time_col).reset_index(drop=True)

    # temps relatif en secondes
    df_pwm["t_seconds"] = (df_pwm[time_col] - df_pwm[time_col].iloc[0]) * 24 * 3600

    # binaire
    df_pwm["gateState_num"] = (df_pwm[gate_col].fillna(0) > 0).astype(int)
    df_pwm["gateState_prev"] = df_pwm["gateState_num"].shift(1).fillna(0).astype(int)

    # front montant
    df_pwm["rising_edge"] = (
        (df_pwm["gateState_num"] == 1) &
        (df_pwm["gateState_prev"] == 0)
    ).astype(int)

    # compteur de cycles
    df_pwm["cycle_current"] = df_pwm["rising_edge"].cumsum()

    # renommage uniforme pour la suite
    df_pwm = df_pwm.rename(columns={time_col: "timeEpoch"})

    return df_pwm

### 3.4 Association du cycle aux lignes `steady`

On fait ensuite un `merge_asof` entre `steady` et `pwm` sur `timeEpoch`, avec `direction="backward"`.

Cela veut dire :

> pour chaque ligne `steady`, on récupère le dernier cycle connu dans `pwm` juste avant cet instant.

C'est exactement la logique de ton notebook.

In [7]:
def attach_cycles_to_steady(df_steady, df_pwm_cycles):
    df_steady = df_steady.copy()

    time_col = find_column(df_steady.columns, ["timeEpoch", "time_epoch", "time"])
    df_steady[time_col] = pd.to_numeric(df_steady[time_col], errors="coerce")
    df_steady = df_steady.dropna(subset=[time_col]).sort_values(time_col).reset_index(drop=True)
    df_steady = df_steady.rename(columns={time_col: "timeEpoch"})

    df_steady = pd.merge_asof(
        df_steady,
        df_pwm_cycles[["timeEpoch", "cycle_current", "t_seconds"]],
        on="timeEpoch",
        direction="backward"
    )

    df_steady["steady_t_seconds"] = (
        (df_steady["timeEpoch"] - df_steady["timeEpoch"].iloc[0]) * 24 * 3600
    )

    return df_steady

### 3.5 Calcul de `RDS_on_raw` et agrégation par cycle

Ici, on calcule :

\[
R_{DS(on), raw} = \frac{V_{DS}}{I_D}
\]

puis on agrège **par cycle** à l'intérieur de chaque run.

L'idée est la suivante :

- plusieurs lignes `steady` peuvent correspondre au même cycle
- on veut une représentation plus compacte et plus cohérente
- donc on résume chaque cycle par des statistiques robustes (ici surtout des médianes)

À la fin :
- **1 ligne = 1 cycle d'un run**

In [8]:
def build_cycle_aggregated_table(df_steady_with_cycle, run_id, current_min=1.0):
    df = df_steady_with_cycle.copy()

    # Détection souple des colonnes utiles
    current_col = find_column(df.columns, ["drainCurrent", "drain_current", "id"])
    vds_col = find_column(df.columns, ["drainSourceVoltage", "drain_source_voltage", "vds"])

    pkg_temp_col = find_column(df.columns, ["packageTemperature", "package_temperature"], required=False)
    flange_temp_col = find_column(df.columns, ["flangeTemperature", "flange_temperature"], required=False)
    supply_col = find_column(df.columns, ["supplyVoltage", "supply_voltage"], required=False)

    # conversion numérique
    for col in [current_col, vds_col, pkg_temp_col, flange_temp_col, supply_col, "cycle_current"]:
        if col is not None and col in df.columns:
            df[col] = pd.to_numeric(df[col], errors="coerce")

    # RDS_on brut
    df["RDS_on_raw"] = df[vds_col] / df[current_col].replace(0, np.nan)

    # filtres simples
    df = df.dropna(subset=["cycle_current", "RDS_on_raw", current_col, vds_col]).copy()
    df = df[df["cycle_current"] > 0].copy()
    df = df[df[current_col] > current_min].copy()

    agg_spec = {
        "timeEpoch": ("timeEpoch", "median"),
        "steady_t_seconds": ("steady_t_seconds", "median"),
        "t_seconds": ("t_seconds", "median"),
        "RDS_on_raw_cycle": ("RDS_on_raw", "median"),
        "RDS_on_raw_mean": ("RDS_on_raw", "mean"),
        "drainCurrent_cycle": (current_col, "median"),
        "drainSourceVoltage_cycle": (vds_col, "median"),
        "n_rows_steady": ("RDS_on_raw", "size"),
    }

    if pkg_temp_col is not None:
        agg_spec["packageTemperature_cycle"] = (pkg_temp_col, "median")
    if flange_temp_col is not None:
        agg_spec["flangeTemperature_cycle"] = (flange_temp_col, "median")
    if supply_col is not None:
        agg_spec["supplyVoltage_cycle"] = (supply_col, "median")

    df_cycle = (
        df.groupby("cycle_current", as_index=False)
          .agg(**agg_spec)
          .sort_values("cycle_current")
          .reset_index(drop=True)
    )

    df_cycle["run_id"] = run_id
    df_cycle["test_id"] = TEST_ID

    # ordre des colonnes
    preferred_first = ["test_id", "run_id", "cycle_current"]
    other_cols = [c for c in df_cycle.columns if c not in preferred_first]
    df_cycle = df_cycle[preferred_first + other_cols]

    return df_cycle, df

## 4. Traitement run par run

Dans cette partie, on applique exactement la même logique aux **Run 1, 2 et 3** :

- chargement des blocs
- reconstruction du cycle dans `pwm`
- association au `steady`
- agrégation par cycle

In [9]:
run_objects = {}
df_all_cycles_parts = []

for run_id in RUN_IDS:
    print("=" * 90)
    print(f"TRAITEMENT DU RUN {run_id}")
    print("=" * 90)

    df_pwm_raw, df_steady_raw, df_transient_raw = load_run_csvs(DATA_DIR, TEST_ID, run_id)

    print("\nDimensions brutes :")
    print(" - pwm      :", df_pwm_raw.shape)
    print(" - steady   :", df_steady_raw.shape)
    print(" - transient:", df_transient_raw.shape)

    df_pwm_cycles = reconstruct_cycles_from_pwm(df_pwm_raw)
    df_steady_with_cycle = attach_cycles_to_steady(df_steady_raw, df_pwm_cycles)
    df_cycle_agg, df_steady_filtered = build_cycle_aggregated_table(
        df_steady_with_cycle, run_id=run_id, current_min=CURRENT_MIN
    )

    run_objects[run_id] = {
        "df_pwm_raw": df_pwm_raw,
        "df_steady_raw": df_steady_raw,
        "df_transient_raw": df_transient_raw,
        "df_pwm_cycles": df_pwm_cycles,
        "df_steady_with_cycle": df_steady_with_cycle,
        "df_steady_filtered": df_steady_filtered,
        "df_cycle_agg": df_cycle_agg,
    }

    df_all_cycles_parts.append(df_cycle_agg)

    print("\nAperçu PWM avec cycle reconstruit :")
    display(df_pwm_cycles.head())

    print("\nAperçu STEADY après association au cycle :")
    display(df_steady_with_cycle.head())

    print("\nTableau agrégé par cycle pour ce run :")
    display(df_cycle_agg.head())

    print("\nNombre de cycles retenus :", len(df_cycle_agg))
    print("Cycle min / max          :", df_cycle_agg["cycle_current"].min(), "/", df_cycle_agg["cycle_current"].max())

==========================================================================================
TRAITEMENT DU RUN 1
==========================================================================================

Dimensions brutes :
 - pwm      : (1345, 11)
 - steady   : (5184, 8)
 - transient: (2728, 8)

Aperçu PWM avec cycle reconstruit :

,time,timeEpoch,nanosec_time,lowTemp,highTemp,shutdownTemp,gateVoltage,supplyVoltage,switchingFrequency,dutyCycle,gateState,t_seconds,gateState_num,gateState_prev,rising_edge,cycle_current
0,03/11/2010 16:21:56.220,734208.681901,0.221,39,40,280,10,5,1000,40,0,0.000000,0,0,0,0
1,03/11/2010 16:21:56.470,734208.681904,0.471,39,40,280,10,5,1000,40,0,0.249999,0,0,0,0
2,03/11/2010 16:21:58.154,734208.681923,0.155,39,40,280,10,5,1000,40,1,1.933997,1,0,1,1
3,03/11/2010 16:22:06.954,734208.682025,0.955,39,40,280,10,5,1000,40,0,10.733999,0,1,0,1
4,03/11/2010 16:22:07.388,734208.682030,0.389,39,40,280,10,5,1000,40,1,11.167994,1,0,1,2

Aperçu STEADY après association au cycle :

,date,nanosec_time,timeEpoch,supplyVoltage,packageTemperature,drainSourceVoltage,drainCurrent,flangeTemperature,cycle_current,t_seconds,steady_t_seconds
0,03/11/2010 16:21:56.867,0.8675,734208.681908,5.603689,29.788117,4.508691,5.179959,28.357752,0,0.249999,0.000000
1,03/11/2010 16:21:57.148,0.1485,734208.681911,5.604414,29.740844,4.531044,5.069381,32.884101,0,0.249999,0.280998
2,03/11/2010 16:21:57.550,0.5505,734208.681916,5.603912,29.867283,4.522496,5.076847,39.873114,0,0.249999,0.682998
3,03/11/2010 16:21:57.946,0.9465,734208.681921,5.604512,30.085515,4.539330,4.989771,46.263143,0,0.249999,1.078992
4,03/11/2010 16:21:58.455,0.4555,734208.681927,5.620543,30.652142,5.577962,0.087613,51.094008,1,1.933997,1.587992

Tableau agrégé par cycle pour ce run :

,test_id,run_id,cycle_current,timeEpoch,steady_t_seconds,t_seconds,RDS_on_raw_cycle,RDS_on_raw_mean,drainCurrent_cycle,drainSourceVoltage_cycle,n_rows_steady,packageTemperature_cycle,flangeTemperature_cycle,supplyVoltage_cycle
0,9,1,1,734208.682029,10.439000,10.733999,0.903046,0.903046,5.019703,4.533022,1,36.052743,40.376827,5.608879
1,9,1,2,734208.682136,19.670996,19.966991,0.854859,0.854859,5.243254,4.482244,1,36.603666,40.514602,5.603089
2,9,1,3,734208.682263,30.678993,30.978991,0.851112,0.851112,5.261381,4.478025,1,36.527576,40.481970,5.603061
3,9,1,4,734208.682398,42.317996,42.612000,0.843240,0.843240,5.299018,4.468342,1,36.534862,40.428717,5.603131
4,9,1,5,734208.682537,54.356997,54.653998,0.873469,0.873469,5.157148,4.504611,1,36.580354,40.509295,5.603354

Nombre de cycles retenus : 668
Cycle min / max          : 1 / 668
==========================================================================================
TRAITEMENT DU RUN 2
==========================================================================================

Dimensions brutes :
 - pwm      : (1468, 11)
 - steady   : (5176, 8)
 - transient: (2737, 8)

Aperçu PWM avec cycle reconstruit :

,time,timeEpoch,nanosec_time,lowTemp,highTemp,shutdownTemp,gateVoltage,supplyVoltage,switchingFrequency,dutyCycle,gateState,t_seconds,gateState_num,gateState_prev,rising_edge,cycle_current
0,03/12/2010 06:00:07.924,734209.250092,0.925,39,40,280,10,5,1000,40,0,0.000000,0,0,0,0
1,03/12/2010 06:00:08.147,734209.250094,0.148,39,40,280,10,5,1000,40,0,0.223002,0,0,0,0
2,03/12/2010 06:00:09.830,734209.250114,0.831,39,40,280,10,5,1000,40,1,1.906005,1,0,1,1
3,03/12/2010 06:00:16.322,734209.250189,0.323,39,40,280,10,5,1000,40,0,8.398003,0,1,0,1
4,03/12/2010 06:00:16.763,734209.250194,0.763,39,40,280,10,5,1000,40,1,8.838999,1,0,1,2

Aperçu STEADY après association au cycle :

,date,nanosec_time,timeEpoch,supplyVoltage,packageTemperature,drainSourceVoltage,drainCurrent,flangeTemperature,cycle_current,t_seconds,steady_t_seconds
0,03/12/2010 06:00:08.543,0.5435,734209.250099,5.600507,29.224404,4.513117,5.165413,27.070524,0,0.223002,0.000000
1,03/12/2010 06:00:08.822,0.8225,734209.250102,5.605112,29.141677,4.517820,5.122663,31.607280,0,0.223002,0.278997
2,03/12/2010 06:00:09.222,0.2225,734209.250107,5.606130,29.241079,4.554767,4.957357,38.710665,0,0.223002,0.678995
3,03/12/2010 06:00:09.624,0.6245,734209.250111,5.606954,29.427095,4.571449,4.866935,45.324103,0,0.223002,1.080994
4,03/12/2010 06:00:10.128,0.1285,734209.250117,5.624129,30.056536,5.581794,0.076046,50.321758,1,1.906005,1.584994

Tableau agrégé par cycle pour ce run :

,test_id,run_id,cycle_current,timeEpoch,steady_t_seconds,t_seconds,RDS_on_raw_cycle,RDS_on_raw_mean,drainCurrent_cycle,drainSourceVoltage_cycle,n_rows_steady,packageTemperature_cycle,flangeTemperature_cycle,supplyVoltage_cycle
0,9,2,1,734209.250193,8.137001,8.398003,0.859682,0.859682,5.219904,4.487458,1,35.049814,40.405630,5.604484
1,9,2,2,734209.250277,15.371995,15.638006,0.871654,0.871654,5.154321,4.492784,1,36.311772,40.377345,5.604023
2,9,2,3,734209.250384,24.599002,24.872003,0.844447,0.844447,5.292867,4.469545,1,36.502483,40.393918,5.604498
3,9,2,4,734209.250500,34.634000,34.900002,0.908835,0.908835,5.002158,4.546135,1,36.344151,40.487674,5.605558
4,9,2,5,734209.250626,45.508997,45.766006,0.861220,0.861220,5.212027,4.488703,1,36.234387,40.476005,5.603954

Nombre de cycles retenus : 730
Cycle min / max          : 1 / 730
==========================================================================================
TRAITEMENT DU RUN 3
==========================================================================================

Dimensions brutes :
 - pwm      : (1434, 11)
 - steady   : (5177, 8)
 - transient: (2583, 8)

Aperçu PWM avec cycle reconstruit :

,time,timeEpoch,nanosec_time,lowTemp,highTemp,shutdownTemp,gateVoltage,supplyVoltage,switchingFrequency,dutyCycle,gateState,t_seconds,gateState_num,gateState_prev,rising_edge,cycle_current
0,03/12/2010 07:20:36.456,734209.305978,0.457,39,40,280,10,5,1000,40,0,0.000000,0,0,0,0
1,03/12/2010 07:20:36.708,734209.305980,0.709,39,40,280,10,5,1000,40,0,0.252000,0,0,0,0
2,03/12/2010 07:20:38.391,734209.306000,0.392,39,40,280,10,5,1000,40,1,1.934993,1,0,1,1
3,03/12/2010 07:20:45.592,734209.306083,0.593,39,40,280,10,5,1000,40,0,9.136000,0,1,0,1
4,03/12/2010 07:20:46.033,734209.306088,0.034,39,40,280,10,5,1000,40,1,9.576995,1,0,1,2

Aperçu STEADY après association au cycle :

,date,nanosec_time,timeEpoch,supplyVoltage,packageTemperature,drainSourceVoltage,drainCurrent,flangeTemperature,cycle_current,t_seconds,steady_t_seconds
0,03/12/2010 07:20:37.104,0.1045,734209.305985,5.602670,30.022700,4.458687,5.348890,27.417590,0,0.252000,0.000000
1,03/12/2010 07:20:37.384,0.3845,734209.305988,5.604526,29.918765,4.497349,5.197978,32.135173,0,0.252000,0.280003
2,03/12/2010 07:20:37.786,0.7865,734209.305993,5.605628,30.111418,4.555334,4.951811,39.378864,0,0.252000,0.682002
3,03/12/2010 07:20:38.183,0.1835,734209.305997,5.605209,30.294358,4.528139,5.035456,46.002366,0,0.252000,1.079002
4,03/12/2010 07:20:38.694,0.6945,734209.306003,5.623920,30.789427,5.581282,0.076305,51.038551,1,1.934993,1.590003

Tableau agrégé par cycle pour ce run :

,test_id,run_id,cycle_current,timeEpoch,steady_t_seconds,t_seconds,RDS_on_raw_cycle,RDS_on_raw_mean,drainCurrent_cycle,drainSourceVoltage_cycle,n_rows_steady,packageTemperature_cycle,flangeTemperature_cycle,supplyVoltage_cycle
0,9,3,1,734209.306087,8.847005,9.136000,0.910239,0.910239,4.996266,4.547795,1,35.992195,40.407440,5.605056
1,9,3,2,734209.306176,16.478004,16.776000,0.849611,0.849611,5.267812,4.475590,1,37.025884,40.418839,5.604330
2,9,3,3,734209.306289,26.225999,26.516996,0.841303,0.841303,5.307650,4.465340,1,37.074614,40.581330,5.604177
3,9,3,4,734209.306410,36.743001,37.039992,0.869623,0.869623,5.163989,4.490723,1,37.009371,40.517303,5.603605
4,9,3,5,734209.306536,47.574003,47.873991,0.846254,0.846254,5.283868,4.471496,1,36.758112,40.519163,5.604149

Nombre de cycles retenus : 712
Cycle min / max          : 1 / 712
==========================================================================================
TRAITEMENT DU RUN 4
==========================================================================================

Dimensions brutes :
 - pwm      : (1478, 11)
 - steady   : (5176, 8)
 - transient: (2418, 8)

Aperçu PWM avec cycle reconstruit :

,time,timeEpoch,nanosec_time,lowTemp,highTemp,shutdownTemp,gateVoltage,supplyVoltage,switchingFrequency,dutyCycle,gateState,t_seconds,gateState_num,gateState_prev,rising_edge,cycle_current
0,03/12/2010 10:28:48.885,734209.436677,0.886,39,40,280,10,5,1000,40,0,0.000000,0,0,0,0
1,03/12/2010 10:28:49.119,734209.436680,0.120,39,40,280,10,5,1000,40,0,0.234006,0,0,0,0
2,03/12/2010 10:28:50.423,734209.436695,0.424,39,40,280,10,5,1000,40,1,1.538002,1,0,1,1
3,03/12/2010 10:28:54.464,734209.436741,0.465,39,40,280,10,5,1000,40,0,5.579008,0,1,0,1
4,03/12/2010 10:28:54.996,734209.436748,0.997,39,40,280,10,5,1000,40,1,6.111001,1,0,1,2

Aperçu STEADY après association au cycle :

,date,nanosec_time,timeEpoch,supplyVoltage,packageTemperature,drainSourceVoltage,drainCurrent,flangeTemperature,cycle_current,t_seconds,steady_t_seconds
0,03/12/2010 10:28:49.513,0.5135,734209.436684,5.603800,30.107533,4.504569,5.191720,28.142770,0,0.234006,0.000000
1,03/12/2010 10:28:49.793,0.7935,734209.436687,5.603242,30.114656,4.485010,5.239326,32.759517,0,0.234006,0.280003
2,03/12/2010 10:28:50.250,0.2505,734209.436693,5.604637,30.215677,4.537864,5.008373,40.882436,0,0.234006,0.737001
3,03/12/2010 10:28:50.720,0.7205,734209.436698,5.622971,30.608593,5.580673,0.077081,45.931933,1,1.538002,1.207004
4,03/12/2010 10:28:51.086,0.0865,734209.436702,5.622134,30.817111,5.579871,0.077384,45.345566,1,1.538002,1.573005

Tableau agrégé par cycle pour ce run :

,test_id,run_id,cycle_current,timeEpoch,steady_t_seconds,t_seconds,RDS_on_raw_cycle,RDS_on_raw_mean,drainCurrent_cycle,drainSourceVoltage_cycle,n_rows_steady,packageTemperature_cycle,flangeTemperature_cycle,supplyVoltage_cycle
0,9,4,1,734209.436747,5.401007,5.579008,0.921134,0.921134,4.948012,4.557782,1,33.936311,41.134213,5.602963
1,9,4,2,734209.436826,12.240006,12.511006,0.848722,0.848722,5.271028,4.473640,1,36.283603,40.384428,5.603312
2,9,4,3,734209.436928,21.076007,21.351001,0.879330,0.879330,5.129115,4.510185,1,36.997877,40.443865,5.604107
3,9,4,4,734209.437049,31.505009,31.786007,0.854434,0.854434,5.244441,4.481026,1,37.134515,40.507272,5.603410
4,9,4,5,734209.437179,42.738000,43.013999,0.876243,0.876243,5.143444,4.506907,1,36.981202,40.518639,5.603633

Nombre de cycles retenus : 735
Cycle min / max          : 1 / 735
==========================================================================================
TRAITEMENT DU RUN 5
==========================================================================================

Dimensions brutes :
 - pwm      : (6506, 11)
 - steady   : (26600, 8)
 - transient: (11911, 8)

Aperçu PWM avec cycle reconstruit :

,time,timeEpoch,nanosec_time,lowTemp,highTemp,shutdownTemp,gateVoltage,supplyVoltage,switchingFrequency,dutyCycle,gateState,t_seconds,gateState_num,gateState_prev,rising_edge,cycle_current
0,03/12/2010 12:00:37.444,734209.500433,0.445,39,40,280,10,5,1000,40,0,0.000000,0,0,0,0
1,03/12/2010 12:00:37.662,734209.500436,0.663,39,40,280,10,5,1000,40,0,0.217993,0,0,0,0
2,03/12/2010 12:00:38.941,734209.500451,0.942,39,40,280,10,5,1000,40,1,1.496994,1,0,1,1
3,03/12/2010 12:00:45.341,734209.500525,0.341,39,40,280,10,5,1000,40,0,7.897000,0,1,0,1
4,03/12/2010 12:00:46.182,734209.500535,0.183,39,40,280,10,5,1000,40,1,8.737993,1,0,1,2

Aperçu STEADY après association au cycle :

,date,nanosec_time,timeEpoch,supplyVoltage,packageTemperature,drainSourceVoltage,drainCurrent,flangeTemperature,cycle_current,t_seconds,steady_t_seconds
0,03/12/2010 12:00:38.053,0.0535,734209.500440,5.586332,31.584324,4.513892,5.045772,29.829957,0,0.217993,0.000000
1,03/12/2010 12:00:38.333,0.3335,734209.500444,5.586764,31.670775,4.498621,5.077991,33.541047,0,0.217993,0.280003
2,03/12/2010 12:00:38.735,0.7355,734209.500448,5.587490,31.822955,4.526286,4.949091,40.014788,0,0.217993,0.682002
3,03/12/2010 12:00:39.236,0.2365,734209.500454,5.621129,32.375173,5.578640,0.089987,46.057199,1,1.496994,1.182995
4,03/12/2010 12:00:39.562,0.5625,734209.500458,5.620250,32.853244,5.577824,0.090397,46.321164,1,1.496994,1.508994

Tableau agrégé par cycle pour ce run :

,test_id,run_id,cycle_current,timeEpoch,steady_t_seconds,t_seconds,RDS_on_raw_cycle,RDS_on_raw_mean,drainCurrent_cycle,drainSourceVoltage_cycle,n_rows_steady,packageTemperature_cycle,flangeTemperature_cycle,supplyVoltage_cycle
0,9,5,1,734209.500530,7.781496,7.897000,0.914349,0.914349,4.953224,4.527109,2,35.779062,41.487425,5.587525
1,9,5,2,734209.500763,27.844498,27.960993,0.859210,0.859210,5.196694,4.463134,2,36.923163,41.624730,5.586492
2,9,5,3,734209.500975,46.214500,43.996995,1.024608,1.021617,4.506143,4.615415,14,40.816861,75.600573,5.591731
3,9,5,4,734209.501034,51.253997,51.229002,1.150958,1.137396,4.095673,4.713950,3,56.403877,98.501668,5.593517
4,9,5,5,734209.501076,54.884997,54.865001,1.103039,1.098368,4.236960,4.673532,3,63.271234,99.141929,5.593573

Nombre de cycles retenus : 3248
Cycle min / max          : 1 / 3248
==========================================================================================
TRAITEMENT DU RUN 6
==========================================================================================

Dimensions brutes :
 - pwm      : (8612, 11)
 - steady   : (35422, 8)
 - transient: (16977, 8)

Aperçu PWM avec cycle reconstruit :

,time,timeEpoch,nanosec_time,lowTemp,highTemp,shutdownTemp,gateVoltage,supplyVoltage,switchingFrequency,dutyCycle,gateState,t_seconds,gateState_num,gateState_prev,rising_edge,cycle_current
0,03/12/2010 17:36:48.403,734209.733894,0.404,39,40,280,10,5,1000,40,0,0.000000,0,0,0,0
1,03/12/2010 17:36:48.657,734209.733896,0.657,39,40,280,10,5,1000,40,0,0.254002,0,0,0,0
2,03/12/2010 17:36:51.047,734209.733924,0.048,39,40,280,10,5,1000,40,1,2.644001,1,0,1,1
3,03/12/2010 17:37:11.447,734209.734160,0.447,39,40,280,10,5,1000,40,0,23.044001,0,1,0,1
4,03/12/2010 17:37:12.278,734209.734170,0.279,39,40,280,10,5,1000,40,1,23.874996,1,0,1,2

Aperçu STEADY après association au cycle :

,date,nanosec_time,timeEpoch,supplyVoltage,packageTemperature,drainSourceVoltage,drainCurrent,flangeTemperature,cycle_current,t_seconds,steady_t_seconds
0,03/12/2010 17:36:49.072,0.0725,734209.733901,5.598889,30.321556,4.736275,4.038809,27.319973,0,0.254002,0.000000
1,03/12/2010 17:36:49.354,0.3545,734209.733905,5.591773,30.379675,4.681541,4.218379,30.648373,0,0.254002,0.282004
2,03/12/2010 17:36:49.754,0.7545,734209.733909,5.591131,30.832653,4.710077,4.102471,36.688855,0,0.254002,0.682002
3,03/12/2010 17:36:50.156,0.1565,734209.733914,5.592820,31.691497,4.712650,4.080071,42.551733,0,0.254002,1.084001
4,03/12/2010 17:36:51.347,0.3475,734209.733928,5.621562,35.637648,5.579000,0.087721,56.340409,1,2.644001,2.275003

Tableau agrégé par cycle pour ce run :

,test_id,run_id,cycle_current,timeEpoch,steady_t_seconds,t_seconds,RDS_on_raw_cycle,RDS_on_raw_mean,drainCurrent_cycle,drainSourceVoltage_cycle,n_rows_steady,packageTemperature_cycle,flangeTemperature_cycle,supplyVoltage_cycle
0,9,6,1,734209.734166,22.863500,23.044001,1.191632,1.191632,3.977736,4.736047,2,36.956351,41.164862,5.596015
1,9,6,2,734209.734421,44.899505,45.073000,1.153745,1.153745,4.078452,4.705450,2,36.744190,41.203766,5.592757
2,9,6,3,734209.734608,61.087005,58.712003,1.244971,1.245826,3.818926,4.765061,15,44.674213,75.415782,5.594689
3,9,6,4,734209.734669,66.324002,66.360000,1.318860,1.325785,3.642485,4.803930,3,62.200471,97.430720,5.596447
4,9,6,5,734209.734706,69.553002,69.596997,1.394933,1.387934,3.474503,4.846699,3,66.408891,98.589606,5.597159

Nombre de cycles retenus : 4301
Cycle min / max          : 1 / 4301
==========================================================================================
TRAITEMENT DU RUN 7
==========================================================================================

Dimensions brutes :
 - pwm      : (8817, 11)
 - steady   : (35397, 8)
 - transient: (17726, 8)

Aperçu PWM avec cycle reconstruit :

,time,timeEpoch,nanosec_time,lowTemp,highTemp,shutdownTemp,gateVoltage,supplyVoltage,switchingFrequency,dutyCycle,gateState,t_seconds,gateState_num,gateState_prev,rising_edge,cycle_current
0,03/13/2010 17:03:32.708,734210.710795,0.709,39,40,280,10,5,1000,40,0,0.000000,0,0,0,0
1,03/13/2010 17:03:32.934,734210.710798,0.934,39,40,280,10,5,1000,40,0,0.226000,0,0,0,0
2,03/13/2010 17:03:34.619,734210.710817,0.620,39,40,280,10,5,1000,40,1,1.910993,1,0,1,1
3,03/13/2010 17:03:40.218,734210.710882,0.219,39,40,280,10,5,1000,40,0,7.509997,0,1,0,1
4,03/13/2010 17:03:41.052,734210.710892,0.053,39,40,280,10,5,1000,40,1,8.344000,1,0,1,2

Aperçu STEADY après association au cycle :

,date,nanosec_time,timeEpoch,supplyVoltage,packageTemperature,drainSourceVoltage,drainCurrent,flangeTemperature,cycle_current,t_seconds,steady_t_seconds
0,03/13/2010 17:03:33.332,0.3325,734210.710802,5.596489,29.491043,4.771147,3.809992,26.297252,0,0.226000,0.000000
1,03/13/2010 17:03:33.613,0.6135,734210.710806,5.602558,29.551753,4.811565,3.626926,29.228058,0,0.226000,0.280998
2,03/13/2010 17:03:34.012,0.0125,734210.710810,5.599754,30.112389,4.799489,3.673302,34.798897,0,0.226000,0.680000
3,03/13/2010 17:03:34.413,0.4135,734210.710815,5.596866,31.034048,4.806876,3.659534,40.382328,0,0.226000,1.081004
4,03/13/2010 17:03:34.916,0.9165,734210.710821,5.622455,32.909097,5.580092,0.082584,45.569025,1,1.910993,1.583999

Tableau agrégé par cycle pour ce run :

,test_id,run_id,cycle_current,timeEpoch,steady_t_seconds,t_seconds,RDS_on_raw_cycle,RDS_on_raw_mean,drainCurrent_cycle,drainSourceVoltage_cycle,n_rows_steady,packageTemperature_cycle,flangeTemperature_cycle,supplyVoltage_cycle
0,9,7,1,734210.710888,7.378003,7.509997,1.318650,1.318650,3.648161,4.807554,2,35.677636,40.368603,5.596712
1,9,7,2,734210.711041,20.650999,20.778996,1.355752,1.355752,3.565400,4.828655,2,36.456748,40.917197,5.600263
2,9,7,3,734210.711268,40.185499,40.317997,1.340013,1.340013,3.598558,4.816067,2,36.239406,40.916831,5.600382
3,9,7,4,734210.711374,49.354500,46.751999,1.440272,1.417402,3.375967,4.862254,16,46.262873,76.520906,5.599908
4,9,7,5,734210.711437,54.793004,54.784998,1.516099,1.520983,3.231400,4.899124,3,64.776034,97.770654,5.600005

Nombre de cycles retenus : 4404
Cycle min / max          : 1 / 4404

## 5. Affichage détaillé des tableaux agrégés run par run

In [ ]:
for run_id in RUN_IDS:
    print("#" * 100)
    print(f"TABLEAU AGREGÉ — TEST {TEST_ID} RUN {run_id}")
    print("#" * 100)
    display(run_objects[run_id]["df_cycle_agg"])

## 6. Tableau concaténé final

On concatène maintenant les trois tables agrégées.

La logique finale est donc bien :

- `run_id` = **unit**
- `cycle_current` = **temps**
- **1 ligne = 1 cycle d'un run**

In [ ]:
df_all_cycles = pd.concat(df_all_cycles_parts, ignore_index=True)

print("Dimensions du tableau concaténé :", df_all_cycles.shape)
display(df_all_cycles.head(20))

## 7. Vérification de la structure Unit / Cycle

Ici, on vérifie que pour chaque run :
- les cycles sont bien ordonnés
- la structure est cohérente

In [ ]:
summary = (
    df_all_cycles.groupby("run_id")
    .agg(
        n_cycles=("cycle_current", "count"),
        cycle_min=("cycle_current", "min"),
        cycle_max=("cycle_current", "max"),
        rds_min=("RDS_on_raw_cycle", "min"),
        rds_max=("RDS_on_raw_cycle", "max"),
    )
    .reset_index()
)

display(summary)

## 8. Visualisation simple

On visualise l'évolution de `RDS_on_raw_cycle` en fonction du cycle pour chaque run.

In [ ]:
if SHOW_PLOTS:
    plt.figure(figsize=(10, 5))
    for run_id in RUN_IDS:
        tmp = run_objects[run_id]["df_cycle_agg"]
        plt.plot(tmp["cycle_current"], tmp["RDS_on_raw_cycle"], label=f"Run {run_id}")
    plt.xlabel("Cycle")
    plt.ylabel("RDS_on_raw_cycle")
    plt.title("Evolution de RDS_on par cycle pour Test 9 Run 1 à 3")
    plt.grid(True)
    plt.legend()
    plt.show()

## 9. Sauvegarde des tableaux agrégés

On enregistre :
- un CSV agrégé par cycle pour chaque run
- un CSV concaténé final

Cela facilitera le prochain notebook, par exemple pour :
- la normalisation
- le lissage
- la construction des séquences
- la préparation du LSTM

In [ ]:
OUT_DIR = DATA_DIR

for run_id in RUN_IDS:
    fp = os.path.join(OUT_DIR, f"Test_{TEST_ID}_run_{run_id}_cycle_agg.csv")
    run_objects[run_id]["df_cycle_agg"].to_csv(fp, index=False)
    print("Sauvegardé :", fp)

fp_all = os.path.join(OUT_DIR, f"Test_{TEST_ID}_runs_1_to_3_cycle_agg_concat.csv")
df_all_cycles.to_csv(fp_all, index=False)
print("Sauvegardé :", fp_all)

## 10. Conclusion de cette étape

À ce stade, le prétraitement demandé pour cette partie est fait :

1. les cycles ont été reconstruits à partir du bloc `pwm`
2. les lignes `steady` ont été rattachées aux cycles
3. les données ont été agrégées **par cycle et par run**
4. on a obtenu une structure de type **Unit / Cycle**

### Ce qu'il faut retenir

- **Unit = run_id**
- **Cycle = cycle_current**
- **une ligne finale = un cycle dans un run**

C'est cette structure qui servira proprement dans la suite.